// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/login.post').default>>>>
    }
    '/api/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login.post').default>>>>
    }
    '/api/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/logout.post').default>>>>
    }
    '/api/user': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user.get').default>>>>
    }
    '/api/wallet-types': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wallet-types/index.get').default>>>>
    }
    '/api/wallet-users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wallet-users/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wallet-users/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wallet-users/[id].put').default>>>>
    }
    '/api/wallet-users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wallet-users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wallet-users/index.post').default>>>>
    }
    '/api/wallets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wallets/index.get').default>>>>
    }
    '/login/google/callback': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/login/google/callback.get').default>>>>
    }
    '/login/google': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/login/google/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}