// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/13/2026, 6:55:00 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Volumes/APRIL_SSD/APRIL/fintrack/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/APRIL_SSD/APRIL/fintrack/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/APRIL_SSD/APRIL/fintrack/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/APRIL_SSD/APRIL/fintrack/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/APRIL_SSD/APRIL/fintrack/app/plugins/**/*.{js,ts,mjs}","/Volumes/APRIL_SSD/APRIL/fintrack/app/composables/**/*.{js,ts,mjs}","/Volumes/APRIL_SSD/APRIL/fintrack/app/utils/**/*.{js,ts,mjs}","/Volumes/APRIL_SSD/APRIL/fintrack/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/APRIL_SSD/APRIL/fintrack/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Volumes/APRIL_SSD/APRIL/fintrack/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Volumes/APRIL_SSD/APRIL/fintrack/app/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;